version: "3.9"
services:
          
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - spring

  msvc-cursos:
    container_name: msvc-cursos
    image: bonomiariel1/cursos
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: root		
      USUARIOS_URL: ec2-54-196-253-87.compute-1.amazonaws.com:8001
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always
  
volumes:
  data-postgres:
    name: data-postgres
  
networks:
  spring: 